In [111]:
# Import libraries necessary for this project
import numpy as np
import pandas as pd
from time import time
from IPython.display import display  # Allows the use of display() for DataFrames
from matplotlib import pyplot as plt
import seaborn as sns

# to suppress warnings
import warnings
warnings.filterwarnings("ignore")

# Pretty display for notebooks
%matplotlib inline

data = pd.read_csv("final.csv")

data.head()



sid  in_library_day  in_library_time  room_day  room_time  book_cnt  \
0  11711222              62            19238         0          0         2   
1  11711223              33             9044         1        120         4   
2  11711224               8             2153         0          0        23   
3  11711230               4              606         0          0         7   
4  11711231             142            39454         0          0        36   

   A  B  C  D  ...  O  P  Q  R  S  T  U  V  X  Z  
0  0  0  0  0  ...  0  0  0  0  0  2  0  0  0  0  
1  0  0  0  0  ...  1  0  0  0  0  3  0  0  0  0  
2  2  6  5  0  ...  0  0  0  0  0  0  0  0  0  0  
3  0  0  0  0  ...  3  0  0  0  0  0  0  0  0  0  
4  0  3  0  0  ...  4  0  0  0  0  4  0  0  0  0  

[5 rows x 28 columns]

In [112]:
data.shape

(22203, 28)

In [113]:
# # Visualize skewed continuous features of original data
# plt.figure(1)
# plt.subplot(121)
# sns.distplot(data["book_cnt"])

# plt.subplot(122)
# data["book_cnt"].plot.box(figsize=(16,5))
# plt.show()


In [114]:
# for col in data.columns:
#     display(data[col].unique())

In [115]:
data["book_cnt"] = np.log(data["book_cnt"] + 1)

data["in_library_time"] = np.log(data["in_library_time"] + 1)

data["room_time"] = np.log(data["room_time"] + 1)

data["in_library_day"] = np.log(data["in_library_day"] + 1)

data["room_day"] = np.log(data["room_day"] + 1)

In [116]:
# X = data.drop(["sid"], axis=1)
# X = data[["book_cnt"]]
X = data[["in_library_time", "room_time"]]

X.head()

in_library_time  room_time
0         9.864695   0.000000
1         9.109967   4.795791
2         7.675082   0.000000
3         6.408529   0.000000
4        10.582916   0.000000

In [117]:
num = 3

### KMeans

In [118]:
from sklearn.cluster import KMeans

km = KMeans(n_clusters=num, random_state=0)
km.fit(X)

predict = km.predict(X)

cnts = np.zeros(num)
for i in range(num):
    cnts[i] = np.where(predict == i)[0].shape[0]

cnts 

array([8188., 5745., 8270.])

In [119]:
centers = km.cluster_centers_

display(centers)

array([[1.00699349e+01, 1.91273390e-03],
       [1.07751022e+01, 6.05453270e+00],
       [4.67239506e+00, 1.00163932e-01]])

In [120]:
max_distance = np.zeros((num, X.shape[1]))

for k in range(num):
    cluster_k = X[predict == k]
    max_distance[k] = np.max(np.sqrt((cluster_k - centers[k]) ** 2))

max_distance

array([[3.64911874, 3.0426097 ],
       [6.69756471, 5.21290135],
       [4.67239506, 6.35503463]])

In [121]:
# mean_distance = np.zeros(num)

# for k in range(num):
#     cluster_k = X[predict == k]
#     mean_distance[k] = np.mean(np.sqrt((cluster_k - centers[k]) ** 2))

# mean_distance

In [122]:
# import numpy as np
# from matplotlib import cm
# from sklearn.metrics import silhouette_samples
 
# cluster_labels=np.unique(predict)
# n_clusters=cluster_labels.shape[0]
# silhouette_vals=silhouette_samples(X, predict, metric='euclidean')
 
# y_ax_lower,y_ax_upper=0,0
 
# yticks=[]
 
# for i,c in enumerate(cluster_labels):
#     c_silhouette_vals=silhouette_vals[predict==c]
#     c_silhouette_vals.sort()
    
#     y_ax_upper+=len(c_silhouette_vals)
#     color=cm.jet(i/n_clusters)
    
#     plt.barh(range(y_ax_lower,y_ax_upper),
#             c_silhouette_vals,
#             height=1.0,
#             edgecolor='none',
#             color=color)
#     yticks.append((y_ax_lower+y_ax_upper)/2)
#     y_ax_lower+=len(c_silhouette_vals)
    
# silhouette_avg=np.mean(silhouette_vals)
 
# plt.axvline(silhouette_avg,color='red',linestyle='--')
 
# plt.yticks(yticks,cluster_labels+1)
# plt.ylabel('Cluster')
# plt.xlabel('Silhouette coefficient')

# plt.show()

In [123]:
# # initial once
# result = dict()
# sid_list = data["sid"]
# n_people = len(sid_list)
# for i in range(n_people):
#     result[sid_list[i]] = list()

In [124]:
for i in range(n_people):
    result[sid_list[i]].append(predict[i])

In [125]:
result

{11711222: [0, 0],
 11711223: [1, 1],
 11711224: [1, 0],
 11711230: [1, 2],
 11711231: [1, 0],
 11711232: [0, 2],
 11711233: [0, 2],
 11711234: [1, 0],
 11711235: [1, 0],
 11711301: [1, 0],
 11711302: [1, 0],
 11711303: [1, 0],
 11711304: [1, 0],
 11711305: [0, 2],
 11711306: [1, 0],
 11711307: [0, 1],
 11711308: [1, 0],
 11711309: [1, 0],
 11711310: [1, 0],
 11711311: [1, 0],
 11711312: [1, 0],
 11711313: [1, 0],
 11711314: [1, 0],
 11711315: [0, 2],
 11711316: [0, 2],
 11711317: [1, 2],
 11711318: [0, 0],
 11711319: [1, 0],
 11711320: [1, 2],
 11711321: [1, 0],
 11711322: [1, 0],
 11711323: [1, 0],
 11711324: [0, 1],
 11711330: [1, 0],
 11711331: [1, 0],
 11711332: [1, 0],
 11711333: [1, 0],
 11711334: [1, 1],
 11711335: [1, 0],
 11711401: [1, 1],
 11711402: [1, 2],
 11711403: [0, 0],
 11711405: [1, 2],
 11711406: [1, 0],
 11711407: [0, 0],
 11711408: [1, 0],
 11711409: [0, 2],
 11711410: [1, 0],
 11711411: [0, 1],
 11711412: [0, 0],
 11711413: [1, 0],
 11711414: [1, 0],
 11711415: [

In [134]:
with open("./result.csv", "w") as f:
    for item in result.items():
        sid = item[0]
        first = item[1][0]
        second = item[1][1]
        f.write(str(sid) + "," + str(first) + "," + str(second) + "\n")

### GMM

In [127]:
# from sklearn.mixture import GaussianMixture

# gmm = GaussianMixture(n_components=num, random_state=0).fit(X)

# predict = gmm.predict(X)

# probs = gmm.predict_proba(X)

# cnts = np.zeros(num)
# for i in range(num):
#     cnts[i] = np.where(predict == i)[0].shape[0]

# cnts

In [128]:
# gmm.converged_

In [129]:
# gmm.means_

In [130]:
# gmm.covariances_

In [131]:
# import numpy as np
# from matplotlib import cm
# from sklearn.metrics import silhouette_samples
 
# cluster_labels=np.unique(predict)
# n_clusters=cluster_labels.shape[0]
# silhouette_vals=silhouette_samples(X, predict, metric='euclidean')
 
# y_ax_lower,y_ax_upper=0,0
 
# yticks=[]
 
# for i,c in enumerate(cluster_labels):
#     c_silhouette_vals=silhouette_vals[predict==c]
#     c_silhouette_vals.sort()
    
#     y_ax_upper+=len(c_silhouette_vals)
#     color=cm.jet(i/n_clusters)
    
#     plt.barh(range(y_ax_lower,y_ax_upper),
#             c_silhouette_vals,
#             height=1.0,
#             edgecolor='none',
#             color=color)
#     yticks.append((y_ax_lower+y_ax_upper)/2)
#     y_ax_lower+=len(c_silhouette_vals)
    
# silhouette_avg=np.mean(silhouette_vals)
 
# plt.axvline(silhouette_avg,color='red',linestyle='--')
 
# plt.yticks(yticks,cluster_labels+1)
# plt.ylabel('Cluster')
# plt.xlabel('Silhouette coefficient')
 
# plt.show()

In [132]:
# with open("./result.txt", "w") as f:
#     for prob in probs:
#         f.write(str(prob)+"\n")